### ISSUE TITLE
As a User I want to have a Shop on the right side to do buy new Towers and enemy minions for the multiplayer mode

### ISSUE THREAD

**Issue by Thahit** [sopra-fs21-group-10/td-client#16]
Acceptance criteria:
1. It is possible to click on a tower/minion in the shop and a new window shows up
2. In the window information about the shop item is displayed (e.g. Damage, attack speed, HP, special effects…)
3. In the window is a Button for buying the tower
4. If resources allow to buy, then the gold of the player is updated and displayed and it is possible to place the tower on the playing field
5. If the resources permit the buy, the button is disabled

**Comment by HuberNicolas** [comment]
No multiplayer, just singleplayer: Only possible to buy towers
5d8e1d8f551f67d564fa87174c84f809540e6a01
998560c42f9b24bf67cd7cff26c8860f27b8174d
27cbf9b783713f0a59025affd771803b31e13913
8b655077e870821243dc30f273babc7929e2fc2b
