### ISSUE TITLE
As a player in a game, I want to hover over my placed towers in the playing field and update/sell the tower

### ISSUE THREAD

**Issue by Thahit** [sopra-fs21-group-10/td-client#17]
Acceptance criteria: 
1. By clicking on a tower it can be selected and a small window lists the specific details
2. In the window there is the option to update/sell a tower
3. Update and sell actions can be executed and the gold and the tower in the field is updated correctly

**Comment by HuberNicolas** [comment]
f7bcaaa770bcaef15c610a577f18db3f4e951e1c
58b46914406eda7a129c602164857c3f045b3015
b970c9f7fd3ecbcaa77c22d750a98dc39ff64500
