### ISSUE TITLE
The minions have health that goes down when they get attacked until they are dead

### ISSUE THREAD

**Issue by Thahit** [sopra-fs21-group-10/td-client#18]
Acceptance criteria: 
1. The minions health is stored and updated when they get attacked
2. When the minions reach HP<=0 the minion will be removed from the playing field
3. When the minion is finally removed, the player gets a predefined amount of gold

**Comment by HuberNicolas** [comment]
5d8e1d8f551f67d564fa87174c84f809540e6a01
65a8697ae3795b96e7accc129a68ab8ba57dd5f2
7827e2bf8165a53602142780872a7c473803da93
