### ISSUE TITLE
When a minion is not killed and it reaches the end of  the pathway. The player loses health.

### ISSUE THREAD

**Issue by Thahit** [sopra-fs21-group-10/td-client#21]
Acceptance criteria: 
1. When a minion reaches the end of the pathway the remaining health of it is subtracted from the player's health.

**Comment by HuberNicolas** [comment]
5d8e1d8f551f67d564fa87174c84f809540e6a01
58b46914406eda7a129c602164857c3f045b3015
53f38313009c0bf146d663012a43a68ce6b4b456
7827e2bf8165a53602142780872a7c473803da93
