### ISSUE TITLE
designing the registration form and sending the registration request

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs21-group-10/td-client#27]
- making a form for getting the user input(the username and password)
- sending the request (/users | post | Username <str> , password <str>)
- depending on the returned status code the login was succesful (redirect to login or directly login) or unsuccesfull (appropriate error message is displayed

Estimated time: 2h
This task is part of user story with issue number #2

**Comment by Seouless29** [comment]
d4df086b13b20bf0c81c10c484efbea592074574
