### ISSUE TITLE
Create a form to perform the login request

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs21-group-10/td-client#29]
- creating a new page for the login
- creating a form for user input (username, password)
- sending the login request (/users/logins | post | Username <str> , password <str>)
- depending on the return status either the appropriate error message gets displayed or the user is logged in and rerouted to the Main Menu

Estimated time: 3h
This task is part of user story with issue number #3

**Comment by Seouless29** [comment]
755b7d4f8775387ad2bce02f49418f189569fda4
