### ISSUE TITLE
Button to create a new Lobby and send request

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs21-group-10/td-client#30]
- button to create a new lobby
- clicking the button sends (/lobbies | post | userid<long>) if successfully (redirect to the lobby page) if unsuccessfully(show error message and stay in main menu)

Estimated time: 2h
This task is part of user story with issue number #5

**Comment by Seouless29** [comment]
as soon as back end is ready, the request can be made.

**Comment by Seouless29** [comment]
59f9faf0460dfbf99b579fee1e30a4884925ba5d
