### ISSUE TITLE
created lobbys are visible in the lobby overview

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs21-group-10/td-client#34]
- in the lobby overview all lobbys are displayed
- for every lobby it displays information(hostname, status and how much people are in the lobby)

Estimated time: 4h
This task is part of user story with issue number #5

**Comment by Seouless29** [comment]
Only the lobby is displayed. further information are following as we see which ones are needed. for now only the basic information is displayed for simplicity.

**Comment by Seouless29** [comment]
55081ca5caa130c32c63438aeaf43e633c753515
