### ISSUE TITLE
leave button that updates the lobby and redirects to player to lobby overview

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs21-group-10/td-client#37]
- create leave button in the lobby
- pressing the leave button sends a put request with userId, lobbyId
- only if the request was sucessful the player gets redirected to the lobby overview

Estimated time: 2h
This task is part of user story with issue number #7

**Comment by Seouless29** [comment]
b4fd79b3306276e765d8a6b958276e9f3df88300

**Comment by Seouless29** [comment]
b4fd79b3306276e765d8a6b958276e9f3df88300
