### ISSUE TITLE
Minion reaching end of pathway

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#44]
- When a minion reaches the end of the pathway, the player will lose health points.

Expected time: 1h
This task is part of user story #21

**Comment by HuberNicolas** [comment]
First version done, still needs a lot of improvement
(no collision detection, no sweep, resolution very bad)

**Comment by HuberNicolas** [comment]
48ca0db9e1d24d9ddbec14e4f56cdcdd92e02664
2916bab94abad1f8f4df002c0e5a8257d3403b18
a8fed13c07cfcfb4cb08df42e35f3fdc280ed9a2
