### ISSUE TITLE
Earning passive income

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#45]
- When the player earns passive income, this will be reflected by updating the "Gold" value in the status bar above the playing field

Estimated time: 1h
This task is part of user story #20

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-server/commit/a2a1b25f25658d23b15969aea80b9eb5432c4f70
implemented in backend(+10% at the beginning of battle phase), can see new gold count with normal get request
