### ISSUE TITLE
Attacking minions

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#46]
- When a minion comes into a tower's attack range, the tower will attack him.
- When a projectile hits a minion, the client will send a PATCH request to /games/ {gameId)/{token} to inform the server about the hit
- After killing a minion, the tower will attack the next minion that is nearest to it within its range.

Estimated time: 6h
This task is part of user story #19

**Comment by HuberNicolas** [comment]
4a6e30576e2474abe1b2facc4c91382c151969bb
bd5fd3b5edd3b00a887ce7336fc52480d9ea5f3a

**Comment by HuberNicolas** [comment]
5d8e1d8f551f67d564fa87174c84f809540e6a01
65a8697ae3795b96e7accc129a68ab8ba57dd5f2
244091101453d46c55edee2fbf092825aeba630d
