### ISSUE TITLE
access to shop during preparation phase

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#50]
- During the preparation phase, the player can use the shop to upgrade, buy and sell towers.
- Upgrading, buying or selling a tower will send the appropriate REST request to the server.
- The status bar will be updated at the next /games/{gameId} update

Estimated time: 7h
This task is part of user story #14

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-client/commit/3f2067e50f1a5adee766c370c47410ca173c7c60
