### ISSUE TITLE
Showing the status bar

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#51]
- While playing the game, a status bar containing all stats of the player and game (e.g. Wave number, gold, player health, weather, remaining minions in the round…) is displayed above the playing field at all times.
- The status bar always displays the correct information by being frequently updated by means of GET /games/{gameId} requests

Estimated time: 4h
This task is part of user story #13

**Comment by HuberNicolas** [comment]
Simple version done, need some love to enhance the look

**Comment by HuberNicolas** [comment]
Has one indicator (HP in it), we still need to add multiple states.

**Comment by HuberNicolas** [comment]
08eb6f016d8bb155bfee02bd145729d67e131b29
3406a66bcfe9c7ee5d1a7121ee186d084c3828df

**Comment by HuberNicolas** [comment]
6c1ea04e7f054294aea4e9008effde35e493bd5e
d1a79f01025248d78d47f98a3bc2334e39c1f7db
093335e2fcd98e0e1ce80ec3fc17aa5c3d8da493
