### ISSUE TITLE
Rendering the playing field

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#52]
- When starting a new game, send a GET /games/{gameId} request to get information about the playing field
- Render the playing field with static and dynamic tiles based on the returned data

Estimated time: 10h
This task is part of user story #12

**Comment by HuberNicolas** [comment]
Simple version done, need some love to enhance the look

**Comment by HuberNicolas** [comment]
Improved Version, still need a lot of improvement.
Defined datastructure for backend.

**Comment by HuberNicolas** [comment]
a43fc9db62cdad4178204c5839d9ad3a06ef06d3
6a6a1e4a92b54bded2d1293f0a9fcb3e40dcb887
4430164853419dd11d4ca8db1b2f93514209eed8
e3fb3ae24959f0e5f1daeb0e3c1b125cf367eb4a
3406a66bcfe9c7ee5d1a7121ee186d084c3828df
030f22206155a49b07955b75c97ae2db3cc700fa

**Comment by HuberNicolas** [comment]
5d8e1d8f551f67d564fa87174c84f809540e6a01
58b46914406eda7a129c602164857c3f045b3015
0b123e517b90d79f7c50793e1ce480a4009b9e6b
04dc9505af13ee5fcf10860fd7c5d2cbcdb38224
