### ISSUE TITLE
Rendering the shop

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#53]
- When starting a new game, create and render the shop to the right of the playing field
- It is possible to scroll through the available shop items
- Shop elements like tower & minions (only in multiplayer) are displayed.

Estimated time: 9h
This task is part of user story #11

**Comment by HuberNicolas** [comment]
Simple version done, need some love to enhance the look

**Comment by HuberNicolas** [comment]
08eb6f016d8bb155bfee02bd145729d67e131b29

**Comment by HuberNicolas** [comment]
998560c42f9b24bf67cd7cff26c8860f27b8174d
f74b10659b3649161c1484ad717516376e4c7dbc
