### ISSUE TITLE
Start of multiplayer game

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#54]
- As a host of a multiplayer lobby, I can start a multiplayer game by clicking the "Play" button in the lobby. This will send a POST /games request to the server to create a new game.
- The game is only started when all the players in the lobby except for the host have clicked on the "Ready" button. This is checked through a GET /lobbies request.
- If there are players in the lobby who have not clicked the "Ready" button when the host tries to start the game, an error message (not all players are ready) will be shown to the host.

Estimated time: 10h
This task is part of user story #10

**Comment by Thahit** [comment]
cancelled
