### ISSUE TITLE
Buying and placing towers/minions

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#56]
- When clicking on a tower or minion in the shop, a new window with information about the shop item is displayed (e.g. Damage, attack speed, HP, special effects…)
- Minions can be bought and are shown in the shop only in multiplayer
- Clicking on the "Buy" button sends a PATCH /games/{gameId)/{token} request to inform the server about the purchase, and receives a confirmation status code in case of a successful purchase
- In case of insufficient funds, the PATCH /games/{gameId)/{token} request returns an "insufficient funds" error message, and the item is not acquired.
- In case of the tower, if the purchase was successful, the player can place it on the map by clicking on a free dynamic tile

Estimated time: 4h
This task is part of user story #16

**Comment by HuberNicolas** [comment]
Added individual projectile to each tower
bd5fd3b5edd3b00a887ce7336fc52480d9ea5f3a

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-client/commit/8b655077e870821243dc30f273babc7929e2fc2b
