### ISSUE TITLE
change user settings

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-client#57]
- In the main menu, there is a button "Edit User Settings"
- A click on "Edit User Settings" redirects to the user settings page where the player can type in a new username, password and location
- The edit request gets sent to PATCH /users/{userid}/{token}. If successful, a confirmation status is returned and the player is redirected back to the main menu. If unsuccessful, an error status is returned and the player can try to type in the new data again.
- When clicking the button "Go back to main menu", the player is taken back to the main menu without any user settings changing.

Estimated time: 2h
This task is part of user story #8

**Comment by Seouless29** [comment]
Fixed several issues related to id

**Comment by Seouless29** [comment]
52474e4616151e82322b315daeb9d94d5af114ff
