### ISSUE TITLE
New miniontype with large amount of hp

### ISSUE THREAD

**Issue by Seouless29** [sopra-fs21-group-10/td-client#64]
- implementation of a minion which can take much more damage than others
- it also deals more damage, should it reach the end of the path (exact value can vary/ balancing is not considered yet)
- it also moves slower than the "normal" minion

Estimated time: 2h

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-client/commit/a0dd99e90abf8c9f1ffdda58aa9fa69a424e1a0f
