### ISSUE TITLE
new miniontype: superminion

### ISSUE THREAD

**Issue by Seouless29** [sopra-fs21-group-10/td-client#66]
- implementation of a minion which spawns several minions upon death
- moves at even slower speed than minion with large amount of health
- if this minon reaches the end of a path, the player loses infinite health resulting in an instant loss

Estimated time: 20h

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-client/commit/a0dd99e90abf8c9f1ffdda58aa9fa69a424e1a0f
