### ISSUE TITLE
balancing the game

### ISSUE THREAD

**Issue by Seouless29** [sopra-fs21-group-10/td-client#70]
- with all the features some turret /minion are stronger than others
- the cost of a minion /turret should be set according to their powerlevel
- the hp of minions and damage of turrets should also be set to a level which does not break the game (e.g. a minion is impossible to kill with the gold a players has to purchase turrets in round x)
- minions which are tougher to kill reward more money

Estimated time: 23h

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-client/commit/155e676114f3731df54af3ba895f2ac8d960a241
