### ISSUE TITLE
better and more clear layout

### ISSUE THREAD

**Issue by Seouless29** [sopra-fs21-group-10/td-client#73]
- background should fit better
- contrast and brightness should be adjusted such that one does not get eyecancer by looking at it

estimated time: 4h

**Comment by HuberNicolas** [comment]
998560c42f9b24bf67cd7cff26c8860f27b8174d
050479333a11ebdc449dfbd093249c8807856cfa
689722536dd60a40a03d027cc88a1a43aeb799c1
244091101453d46c55edee2fbf092825aeba630d
a793915ba99c15a65bdebc805d748c4562858008
8e3f40facd7d33555035075df940b7d410cd15b1
9ee98463009f4f402c5aabed7bd8902c0c45c7e1
1150f1915cefdb8c5ab8b43cad49876260fd1b42
0e8aabe7c93588199916bf3b04c3f3ac1bd6b728
6c1ea04e7f054294aea4e9008effde35e493bd5e
d1a79f01025248d78d47f98a3bc2334e39c1f7db
093335e2fcd98e0e1ce80ec3fc17aa5c3d8da493
