### ISSUE TITLE
preparation phase

### ISSUE THREAD

**Issue by Seouless29** [sopra-fs21-group-10/td-client#78]
- a separation between preparation phase and battle phase
- in the preparation phase minions do not spawn 
- upon pressing "starting round" a request is sent to the backend to retrieve information about the next wave (which minions to spawn)

Estimated time: 6h

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-client/commit/48bbb920c2fd10f504e8f3b2269dd233480f3e21
